### ISSUE TITLE
Closing Price in String

### ISSUE THREAD

**Issue by Taha-Fintech** [MuhammadAmir5670/psx-data-reader#1]
The code is very nicely written but has some issues.

1) Those share which have prices over 1000 have prices reported on website in string that is comma is appearing in values and error is shown that it can't convert it into float. Perhaps string replace needs to be applied.

```
PSX_Scrap_Data = stocks('NESTLE', start=datetime.date(2021, 1, 1), end=datetime.date.today())

~\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py in astype_nansafe(arr, dtype, copy, skipna)
   1199     if copy or is_object_dtype(arr.dtype) or is_object_dtype(dtype):
   1200         # Explicit copy, or required since NumPy can't view from / to object.
-> 1201         return arr.astype(dtype, copy=True)
   1202 
   1203     return arr.astype(dtype, copy=copy)

ValueError: could not convert string to float: '1,166.71'
```

2) sometime an error appears None of ['TIME'] are in the columns
```

~\anaconda3\lib\site-packages\pandas\core\frame.py in set_index(self, keys, drop, append, inplace, verify_integrity)
   5449 
   5450         if missing:
-> 5451             raise KeyError(f"None of {missing} are in the columns")
   5452 
   5453         if inplace:

KeyError: "None of ['TIME'] are in the columns"
```

3) It could have been better that if it bypasses those tickers which have error rather than breaking down the whole process

**Comment by MuhammadAmir5670** [comment]
Hello Taha-Fintech, I hope you are doing great! I'm pleased that you like
this little project of mine and thank you for your great insights, I really
appreciate it, and I'll be looking into these issues and making some
improvements to mitigate such issues.

Once again Thank you,

Regards:
Muhammad Amir Abbasi

**Comment by hasansheikh3** [comment]
Hello Amir, Thank you for this great library, I am a Python beginner and trying to fetch a company's data for a time period of 10 years or so. I am getting the error (which I think is timeout error). Here's my code and Screenshot. Once again Thank you for this library :))
`data = stocks('MEBL',start=datetime.date(2020,1,1),end=datetime.date.today())`
![image](https://user-images.githubusercontent.com/49092528/152926459-51fcefb5-fe27-4a9f-8009-825dad6e3660.png)
![image](https://user-images.githubusercontent.com/49092528/152926496-7b6e24b7-8a3b-492f-8b59-73ac575a9ebe.png)

**Comment by mirfanazam** [comment]
Hi, 

I have encountered this issue and fixed it. Replace line 111 with below line of code.

`data[column] = data[column].str.replace(",", "").astype(np.float64)`

**Comment by MuhammadAmir5670** [comment]
Hello everyone, thanks for using this library and highlighting the issues, Huge shoutout to @mirfanazam for coming up with the solution, and as far as it is concerned about the second issue raised by @Taha-Fintech and @hasansheikh3 related to the KeyError, I have gone over your code, tried myself but for the given examples I didn't find errors on my side, I believe I would need little more information to debug those errors.

![Screenshot from 2022-04-16 17-58-00](https://user-images.githubusercontent.com/62555280/163675877-e5ca10ef-9fbb-4e8a-9d73-27711df91fc1.png)

**Comment by MuhammadAmir5670** [comment]
For the string conversion error, I will be making a new release, once again @mirfanazam thank you for your valuable insights.
