### ISSUE TITLE
Value Error: Time does not match format '%b %d, %Y'

### ISSUE THREAD

**Issue by Muhammad-Uzair-Khan** [MuhammadAmir5670/psx-data-reader#4]
**Hey Amir,**

I am running following simple code that generates error. The code is:

**from psx import stocks, tickers**

**company_abbrev = 'LUCK'**

**data_all = stocks(company_abbrev, start=dt.date(2022, 1, 1), end=dt.date.today())**
**data_all**

The error received is as follows:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-6a7c6e2e3c1b> in <module>
      3 company_abbrev = 'LUCK'
      4 
----> 5 data_all = stocks(company_abbrev, start=dt.date(2022, 1, 1), end=dt.date.today())
      6 data_all

~\Anaconda3\lib\site-packages\psx\web.py in stocks(self, tickers, start, end)
     52         dates = self.daterange(start, end)
     53 
---> 54         data = [self.get_psx_data(ticker, dates)[start: end] for ticker in tickers]
     55 
     56         if len(data) == 1:

~\Anaconda3\lib\site-packages\psx\web.py in <listcomp>(.0)
     52         dates = self.daterange(start, end)
     53 
---> 54         data = [self.get_psx_data(ticker, dates)[start: end] for ticker in tickers]
     55 
     56         if len(data) == 1:

~\Anaconda3\lib\site-packages\psx\web.py in get_psx_data(self, symbol, dates)
     41 
     42                 for future in as_completed(futures):
---> 43                     data.append(future.result())
     44                     progressbar.update(1)
     45 

~\Anaconda3\lib\concurrent\futures\_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433 
    434             self._condition.wait(timeout)

~\Anaconda3\lib\concurrent\futures\_base.py in __get_result(self)
    386     def __get_result(self):
    387         if self._exception:
--> 388             raise self._exception
    389         else:
    390             return self._result

~\Anaconda3\lib\concurrent\futures\thread.py in run(self)
     55 
     56         try:
---> 57             result = self.fn(*self.args, **self.kwargs)
     58         except BaseException as exc:
     59             self.future.set_exception(exc)

~\Anaconda3\lib\site-packages\psx\web.py in download(self, symbol, date)
     65         with session.post(self.__history, data=post) as response:
     66             data = parser(response.text, features="html.parser")
---> 67             data = self.toframe(data)
     68         return data
     69 

~\Anaconda3\lib\site-packages\psx\web.py in toframe(self, data)
     78             for key, value in zip(headers, cols):
     79                 if key == "TIME":
---> 80                     value = datetime.strptime(value, "%b %d, %Y")
     81                 stocks[key].append(value)
     82 

~\Anaconda3\lib\_strptime.py in _strptime_datetime(cls, data_string, format)
    566     """Return a class cls instance based on the input string and the
    567     format string."""
--> 568     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    569     tzname, gmtoff = tt[-2:]
    570     args = tt[:6] + (fraction,)

~\Anaconda3\lib\_strptime.py in _strptime(data_string, format)
    347     found = format_regex.match(data_string)
    348     if not found:
--> 349         raise ValueError("time data %r does not match format %r" %
    350                          (data_string, format))
    351     if len(data_string) != found.end():

**ValueError: time data '469.00' does not match format '%b %d, %Y'**

**Comment by MuhammadAmir5670** [comment]
## A new release in progress
![image](https://user-images.githubusercontent.com/62555280/187037347-abc7e264-8cbb-412d-9d7e-aa0a6e1decd9.png)

**Comment by danishmeh** [comment]
I hope this message finds you well. First of all, thank you for building and sharing the psx Python package — it's a great initiative for making Pakistan Stock Exchange data accessible via code.

I'm reaching out because I've encountered a consistent error when trying to fetch stock data using valid PSX tickers (e.g., "SILK" or "PRL"). I’ve attached the exact code and error message below for your reference. I believe this may be related to missing or changed data structure on the PSX website, which is causing the TIME column to be absent from the parsed result.


import datetime
from psx import stocks

# Attempting to fetch data for a valid ticker "SILK"
data = stocks("SILK", start=datetime.date(2020, 1, 1), end=datetime.date.today())
print(data)
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

KeyError: "None of ['TIME'] are in the columns"

File ...\psx\web.py, line 83, in DataReader.toframe
    return pd.DataFrame(stocks, columns=headers).set_index("TIME")

KeyError: "None of ['TIME'] are in the columns"
